import {
	amberDarkP3,
	amberP3,
	blueDarkP3,
	blueP3,
	brownDarkP3,
	brownP3,
	crimsonDarkP3,
	crimsonP3,
	cyanDarkP3,
	cyanP3,
	grassDarkP3,
	grassP3,
	grayDarkP3,
	grayP3,
	greenDarkP3,
	greenP3,
	indigoDarkP3,
	indigoP3,
	irisDarkP3,
	irisP3,
	jadeDarkP3,
	jadeP3,
	limeDarkP3,
	limeP3,
	mauveDarkP3,
	mauveP3,
	mintDarkP3,
	mintP3,
	oliveDarkP3,
	oliveP3,
	orangeDarkP3,
	orangeP3,
	pinkDarkP3,
	pinkP3,
	plumDarkP3,
	plumP3,
	purpleDarkP3,
	purpleP3,
	redDarkP3,
	redP3,
	rubyDarkP3,
	rubyP3,
	sageDarkP3,
	sageP3,
	sandDarkP3,
	sandP3,
	skyDarkP3,
	skyP3,
	slateDarkP3,
	slateP3,
	tealDarkP3,
	tealP3,
	tomatoDarkP3,
	tomatoP3,
	violetDarkP3,
	violetP3,
	yellowDarkP3,
	yellowP3,
} from "@radix-ui/colors";

export type ArrayOf12<T> = [T, T, T, T, T, T, T, T, T, T, T, T];
export const arrayOf12 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] as const;

export const radixGrayScaleNames = [
	"gray",
	"mauve",
	"slate",
	"sage",
	"olive",
	"sand",
] as const;

export const radixScaleNames = [
	...radixGrayScaleNames,
	"tomato",
	"red",
	"ruby",
	"crimson",
	"pink",
	"plum",
	"purple",
	"violet",
	"iris",
	"indigo",
	"blue",
	"cyan",
	"teal",
	"jade",
	"green",
	"grass",
	"brown",
	"orange",
	"sky",
	"mint",
	"lime",
	"yellow",
	"amber",
] as const;

export const radixScaleColors = {
	gray: grayP3,
	mauve: mauveP3,
	slate: slateP3,
	sage: sageP3,
	olive: oliveP3,
	sand: sandP3,
	tomato: tomatoP3,
	red: redP3,
	ruby: rubyP3,
	crimson: crimsonP3,
	pink: pinkP3,
	plum: plumP3,
	purple: purpleP3,
	violet: violetP3,
	iris: irisP3,
	indigo: indigoP3,
	blue: blueP3,
	cyan: cyanP3,
	teal: tealP3,
	jade: jadeP3,
	green: greenP3,
	grass: grassP3,
	brown: brownP3,
	orange: orangeP3,
	sky: skyP3,
	mint: mintP3,
	lime: limeP3,
	yellow: yellowP3,
	amber: amberP3,
	grayDark: grayDarkP3,
	mauveDark: mauveDarkP3,
	slateDark: slateDarkP3,
	sageDark: sageDarkP3,
	oliveDark: oliveDarkP3,
	sandDark: sandDarkP3,
	tomatoDark: tomatoDarkP3,
	redDark: redDarkP3,
	rubyDark: rubyDarkP3,
	crimsonDark: crimsonDarkP3,
	pinkDark: pinkDarkP3,
	plumDark: plumDarkP3,
	purpleDark: purpleDarkP3,
	violetDark: violetDarkP3,
	irisDark: irisDarkP3,
	indigoDark: indigoDarkP3,
	blueDark: blueDarkP3,
	cyanDark: cyanDarkP3,
	tealDark: tealDarkP3,
	jadeDark: jadeDarkP3,
	greenDark: greenDarkP3,
	grassDark: grassDarkP3,
	brownDark: brownDarkP3,
	orangeDark: orangeDarkP3,
	skyDark: skyDarkP3,
	mintDark: mintDarkP3,
	limeDark: limeDarkP3,
	yellowDark: yellowDarkP3,
	amberDark: amberDarkP3,
} as const;
