export const paletteTokens = [
	"primary-1",
	"primary-2",
	"primary-3",
	"primary-4",
	"primary-5",
	"primary-6",
	"primary-7",
	"primary-8",
	"primary-9",
	"primary-10",
	"primary-11",
	"primary-12",
	"primary-surface",
	"gray-1",
	"gray-2",
	"gray-3",
	"gray-4",
	"gray-5",
	"gray-6",
	"gray-7",
	"gray-8",
	"gray-9",
	"gray-10",
	"gray-11",
	"gray-12",
	"gray-surface",
] as const;

export const extendedTokens = ["color-background", "apple-red"] as const;

export const themeTokens = [...paletteTokens, ...extendedTokens] as const;

export const shadcnCssVariables = [
	"background",
	"foreground",
	"card",
	"card-foreground",
	"popover",
	"popover-foreground",
	"primary",
	"primary-foreground",
	"secondary",
	"secondary-foreground",
	"muted",
	"muted-foreground",
	"accent",
	"accent-foreground",
	"destructive",
	"border",
	"input",
	"ring",
	"chart-1",
	"chart-2",
	"chart-3",
	"chart-4",
	"chart-5",
	"sidebar",
	"sidebar-foreground",
	"sidebar-primary",
	"sidebar-primary-foreground",
	"sidebar-accent",
	"sidebar-accent-foreground",
	"sidebar-border",
	"sidebar-ring",
] as const;

export const scrollbarCssVariables = [
	"scrollbar-thumb",
	"scrollbar-thumb-hover",
	"scrollbar-thumb-active",
] as const;

export const allCssVariables = [
	...shadcnCssVariables,
	...scrollbarCssVariables,
];

export const colorMappings: {
	[K in (typeof allCssVariables)[number]]: (typeof themeTokens)[number];
} = {
	background: "color-background",
	foreground: "gray-12",
	card: "gray-surface",
	"card-foreground": "gray-12",
	popover: "gray-3",
	"popover-foreground": "gray-12",
	primary: "primary-9",
	"primary-foreground": "gray-1",
	secondary: "gray-4",
	"secondary-foreground": "gray-12",
	muted: "gray-2",
	"muted-foreground": "gray-11",
	accent: "primary-5",
	"accent-foreground": "gray-12",
	destructive: "apple-red",
	border: "gray-6",
	input: "gray-3",
	ring: "primary-8",
	"chart-1": "primary-9",
	"chart-2": "primary-5",
	"chart-3": "gray-4",
	"chart-4": "primary-10",
	"chart-5": "gray-7",
	sidebar: "gray-2",
	"sidebar-foreground": "gray-11",
	"sidebar-primary": "primary-10",
	"sidebar-primary-foreground": "gray-12",
	"sidebar-accent": "primary-5",
	"sidebar-accent-foreground": "gray-12",
	"sidebar-border": "gray-7",
	"sidebar-ring": "primary-8",
	"scrollbar-thumb": "gray-6",
	"scrollbar-thumb-hover": "gray-7",
	"scrollbar-thumb-active": "gray-8",
} as const;

export const DEFAULT_INPUT_COLOR = "000000";
